anon/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("auths.urls")),
    path('questions/', include("question.urls"))
]

auths/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login, name='login'),
    path('register', views.register, name='register'),
    path('link', views.link_view, name='link'),
    path('room/<str:room_name>/', views.room_view, name='room'),
]

question/urls.py
from django.urls import path
from . import views

app_name = 'question'
urlpatterns = [

    path('question/', views.create_questions, name='question'),
    path('list_question/', views.list_question, name='list_question'),
    path('construction/', views.construction_view, name='construction')
]

auths/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
import uuid


# Create your models here.
class Details(models.Model):
    username = models.CharField(max_length=56)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False)


class ChatMessage(models.Model):
    room_name = models.CharField(max_length=255)
    message = models.TextField()
    image = models.ImageField(upload_to='message/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Room: {self.room_name}, Message: {self.message}'

question/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Question(models.Model):
    question = models.CharField(max_length=256)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

auths/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Details
from django.core.mail import send_mail
from django.contrib.auth import get_user
from .models import UserProfile
import datetime


# Create your views here.
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        p1 = request.POST['p1']
        p2 = request.POST['p2']
        if p1 == p2:
            if User.objects.filter(email=email).exists():
                messages.info(request, "A User With This Email Already Exist Please Try Another")
                return redirect('register')
            elif User.objects.filter(username=username).exists():
                messages.info(request, "A User With This Username/Nickname Already Exist Please Try Another")
                return redirect('register')
            else:
                user = User.objects.create_user(email=email, password=p1, username=username)
                user.save()
                obj = Details(username=username)
                obj.save()
                subject = "GhostTalker"
                msg = "Email have been confirmed successfully!!"
                to = email
                res = send_mail(subject, msg, "oniyidefaith30@gmail.com", [to])
                if res == 1:
                    return redirect('/')
                else:
                    messages.info(request, "Something went wrong")
                    return redirect('register')
        else:
            messages.info(request, "Password doesn't match try again")
            return redirect('register')
    else:
        return render(request, 'register.html')


def login(request):
    if request.method == 'POST':
        uname = request.POST.get('un', '')
        pass1 = request.POST.get('pa', '')
        user = auth.authenticate(username=uname, password=pass1)
        if user is None:
            messages.info(request, "invalid username/password")
            return redirect('login')
        else:
            auth.login(request, user)
            request.session['user_id'] = user.id  # Store the user's id in the session
            return redirect("link")

    else:
        return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect("login")


def link_view(request):
    unique_id = request.GET.get('id')  # Extract the unique identifier from the URL parameters
    return render(request, 'link.html', {'unique_id': unique_id})


def room_view(request, room_name):
    unique_id = request.GET.get('id')  # Extract the unique identifier from the URL parameters
    user_id = request.session.get('user_id')

    # Retrieve the user object using the stored user ID
    user = get_user(request)

    return render(request, 'chatPage.html',
                  {'room_name': room_name, 'user_id': user_id, 'unique_id': unique_id, 'user': user})

question/views.py
from django.shortcuts import render, redirect
from .models import Question
from django.contrib.auth.decorators import login_required
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated


# Create your views here.

@login_required(login_url="login")
def create_questions(request):
    user_id = request.session.get('user_id')
    if request.method == 'POST':
        question_text = request.POST.get('question', '')
        if question_text:
            question = Question(question=question_text, user=request.user)
            question.save()

    questions = Question.objects.filter(user=request.user)
    return render(request, "question.html", {'questions': questions})


@login_required(login_url="login")
def list_question(request):
    questions = Question.objects.all()
    return render(request, "list_question.html", {'questions': questions})


def construction_view(request):
    return render(request, "construction.html")

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

            <link rel="icon" type="image/x-icon" href="{% static 'svg/incognito.svg' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'auths/login.css' %}">
    <title>
        {% block title %}
        GhostTalk
        {% endblock title %}
    </title>

</head>
<body>

<div class="flex">
    <h2><img src="{% static 'svg/logo.svg' %}"></h2>
<div class="register_container">
            {% block content %}
            {% endblock %}



</div>
<div class="right">
    <div class="content">
    <img class="img" src="{% static 'svg/incognito2.svg' %}"><br>
    <p class="p">Welcome to our anonymous chat application, where you can freely connect with others without revealing your identity. Engage in open conversations, share ideas, and explore diverse perspectives while maintaining complete anonymity.</p>
    </div>
</div>
</div>
</body>
</html>

templates/base2.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>
        {% block title %}
        GhostTalk
         {% endblock title %}
    </title>
     <meta name="viewport">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="icon" type="image/x-icon" href="{% static 'svg/incognito.svg' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'auths/chat.css' %}">
</head>
<body>
<div class="left_menu">
  <div class="left_content">
    <a href="{% url 'login' %}" class="logout">
      <img title="Logout" src="{% static 'svg/incognito.svg' %}" class="hero_logo">
      <span>Logout</span>
    </a>
    <a href="{% url 'room' room_name=request.user %}?id={{ request.session.user_id }}" class="chat">
      <img title="Chat" src="{% static 'svg/chat.svg' %}" class="hero_logo">
      <span>Chat</span>
    </a>
    <a href="{% url 'question:question' %}" class="secret">
      <img title="GhostTalk Question" src="{% static 'svg/question.svg' %}" class="hero_logo">
      <span>Keep Secret</span>
    </a>
    <a href="{% url 'question:construction' %}" class="video">
      <img title="Video Call" src="{% static 'svg/video.svg' %}" class="hero_logo">
      <span>Video</span>
    </a>
  </div>
</div>
<div class="chat_div">
    {% block content %}

    {% endblock %}
</div>

<div class="right_div">
<div class="slideshow-container">

<div class="mySlides fade">
  <div class="numbertext">1 / 2</div>
    <br/>
  <img src="{% static 'svg/logo_two.svg' %}" style="width:100%"><br>
  <div class="text">Welcome To Ghost Talk</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">2 / 2</div><br/><br>
  <img src="https://img.freepik.com/premium-photo/portrait-young-business-man-work-video-call-while-staying-home_58466-15489.jpg?w=740" style="width:100%">
    <br><br>
  <div class="text">Talk with Stranger coming soon</div>
</div>
<br>
<div style="text-align:center">
  <span class="dot"></span>
  <span class="dot"></span>

</div>
</div>
<br>
</div>
<script>
  var roomName = "{{ room_name }}";
  var chatContainer = document.querySelector('.chat_container');
  var messageSendInput = document.querySelector("#id_message_send_input");
  var fileInput = document.querySelector("#id_file_input");
    var wsScheme = window.location.protocol === "https:" ? "wss:" : "ws:";  
if (roomName) {
    var chatSocket = new WebSocket(
        wsScheme + '//' + window.location.host + '/ws/room/' + roomName + '/'
    );
} else {
    console.error("Room name is empty or undefined.");
}
  var messagesFetched = false; 

  chatSocket.onopen = function (event) {
    if (!messagesFetched) {
      chatSocket.send(JSON.stringify({ command: 'fetch_messages' }));
      messagesFetched = true; 
    }
  };

chatSocket.onmessage = function (e) {
    var data = JSON.parse(e.data);
    var message = data.message;
    var isFile = data.is_file;
    var messageElement = document.createElement('div');
    messageElement.classList.add('chats');

    if (isFile) {
        var fileData = data.file_data;
        var fileUrl = URL.createObjectURL(base64ToBlob(fileData, data.file_type));
        var fileElement = document.createElement('img');
        fileElement.classList.add('input_img');
        fileElement.src = fileUrl;
        messageElement.appendChild(fileElement);

        var textCaption = document.createElement('div');
        textCaption.textContent = data.caption;
        messageElement.appendChild(textCaption);
    } else {
        messageElement.textContent = message;
    }

    chatContainer.appendChild(messageElement);
    chatContainer.scrollTop = chatContainer.scrollHeight;
};


function base64ToBlob(base64Data, contentType) {
    var sliceSize = 1024;
    var byteCharacters = atob(base64Data);
    var byteArrays = [];
    for (var offset = 0; offset < byteCharacters.length; offset += sliceSize) {
        var slice = byteCharacters.slice(offset, offset + sliceSize);
        var byteNumbers = new Array(slice.length);
        for (var i = 0; i < slice.length; i++) {
            byteNumbers[i] = slice.charCodeAt(i);
        }
        var byteArray = new Uint8Array(byteNumbers);
        byteArrays.push(byteArray);
    }
    return new Blob(byteArrays, { type: contentType });
}


messageSendInput.focus();
messageSendInput.onkeyup = function (e) {
    if (e.keyCode === 13) {
        sendMessage();
    }
};

fileInput.onchange = function (e) {
    var file = fileInput.files[0];
    var reader = new FileReader();
    reader.onload = function (event) {
        var fileData = event.target.result;
        var messageInput = messageSendInput.value;

        var messageElement = document.createElement('div');
        var fileElement = document.createElement('img');
        fileElement.classList.add('input_img');
        fileElement.src = fileData;
        messageElement.appendChild(fileElement);

        if (messageInput) {
            var textCaption = document.createElement('div');
            textCaption.textContent = messageInput;
            messageElement.appendChild(textCaption);
        }

        messageElement.classList.add('chats');
        chatContainer.appendChild(messageElement);
        chatContainer.scrollTop = chatContainer.scrollHeight;

        chatSocket.send(JSON.stringify({
            command: 'send_file',
            file_data: fileData,
            caption: messageInput
        }));
    };
    reader.readAsDataURL(file);
};

document.querySelector("#id_message_send_button").onclick = function (e) {
    sendMessage();
};

function sendMessage() {
    var messageInput = messageSendInput.value;

    if (messageInput) {
        var messageElement = document.createElement('div');
        messageElement.textContent = messageInput;
        messageElement.classList.add('chats');
        chatContainer.appendChild(messageElement);
        chatContainer.scrollTop = chatContainer.scrollHeight;

        chatSocket.send(JSON.stringify({
            command: 'send_message',
            message: messageInput
        }));
    }

    messageSendInput.value = "";
    fileInput.value = "";
}


const textarea = document.querySelector('textarea');

textarea.addEventListener('input', function () {
  while (textarea.clientHeight < textarea.scrollHeight) {
    textarea.value = textarea.value.substr(0, textarea.value.length - 1);
  }
});

let slideIndex = 0;
showSlides();

function showSlides() {
  let i;
    let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  slideIndex++;
  if (slideIndex > slides.length) {
    slideIndex = 1;
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex - 1].style.display = "block";
  dots[slideIndex - 1].className += " active";
  setTimeout(showSlides, 2000); 
}


function toggleSidebar() {
    const leftMenu = document.querySelector('.left_menu');
    leftMenu.classList.toggle('collapsed');

    const toggleImage = document.querySelector('.toggle');
    const isCollapsed = leftMenu.classList.contains('collapsed');

    if (isCollapsed) {
      toggleImage.src = "{% static 'svg/chevron_right.svg' %}";
    } else {
      toggleImage.src = "{% static 'svg/chevron_left.svg' %}";
    }
  }

</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

templates/chatPage.html
{% extends 'base2.html' %}
{% block content %}
{% load static %}
<img class="toggle" src="{% static 'svg/chevron_left.svg' %}" onclick="toggleSidebar()">
<h3>Hello, Say something about {{room_name}} you're Incognito</h3>
    <br>

    <div class="chat_container"></div>
    <div class="chat__item__container" id="id_chat_item_container" style="font-size: 20px">
        <br />
        <textarea type="text" class="text_area" cols="20" rows="10"  onkeyup="if (this.scrollHeight > this.clientHeight) this.style.height = this.scrollHeight + 'px';"  id="id_message_send_input"></textarea><br>

        <div class="flex_button">
            <input class="hero_logo invisible" type="file" id="id_file_input">
            <button type="submit" class="send_button" id="id_message_send_button">Send</button>
        </div>
        <br />
        <br />
    </div>
{% endblock %}

templates/construction.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
	    <link rel="stylesheet" type="text/css" href="{% static 'auths/construction.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'svg/incognito.svg' %}">

        <title>
        {% block title %}
        GhostTalk
         {% endblock title %}
    </title>
</head>
<body>
<div class="overlay"></div>
<div class="stars" aria-hidden="true"></div>
<div class="starts2" aria-hidden="true"></div>
<div class="stars3" aria-hidden="true"></div>
<main class="main">
	<section class="contact">
		<h1><img src="{% static 'svg/logo_two.svg' %}"></h1><hr>
		<h2 class="sub-title">Page Under Construction</h2>
        <a href="{% url 'question:question' %}" class="logout">
      <img title="Back" src="{% static 'svg/back.svg' %}" class="con_logo">
    </a>
	</section>
</main>
</body>
</html>

templates/link.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GhostTalk</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
            <link rel="icon" type="image/x-icon" href="{% static 'svg/incognito.svg' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'auths/link.css' %}">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body class="link_body">

<div class="link_box">
    <div class="link_content">
        <h2><img src="{% static 'svg/logo.svg' %}"></h2>
        <hr>
        <p>Click the link below to view GhostTalkers or share it to see what your friends have to say</p>
        <div class="copy_div">
            <div class="copy">
                <a href="{% url 'room' room_name=request.user %}?id={{ request.session.user_id }}" target="_blank" id="select_txt">link</a>
            </div>
            <img class="clip" title="Copy Link" typeof="button" onclick="copy_data('select_txt')" id="img" src="{% static 'svg/clipboard.svg' %}">

        </div>
    </div>
</div>
<script>
function copy_data(elementId) {
  var linkElement = document.getElementById(elementId);
  var linkValue = linkElement.getAttribute('href');
  var roomName = "{{ request.user }}";
  var textToCopy = `Say something about ${roomName} you're incognito\n  ${linkValue}`;

  var tempInput = document.createElement("input");
  tempInput.setAttribute("value", textToCopy);
  document.body.appendChild(tempInput);
  tempInput.select();
  document.execCommand("copy");
  document.body.removeChild(tempInput);

  var imgElement = document.getElementById("img");
  imgElement.src = "{% static 'svg/check.svg' %}";
  imgElement.title = "Copied!";
}
</script>
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/list_question.html
{% extends 'base2.html' %}
{% block content %}
{% load static %}
<img class="toggle" src="{% static 'svg/chevron_left.svg' %}" onclick="toggleSidebar()">
<h3>{{request.user}} Keep a secret. I promise i wont tell anyone.</h3>
    <br>

    <div class="chat_container"></div>
    <div class="chat__item__container" id="id_chat_item_container" style="font-size: 20px">
        <br />
<br/>
        <textarea type="text" class="text_area" cols="20" rows="10"  onkeyup="if (this.scrollHeight > this.clientHeight) this.style.height = this.scrollHeight + 'px';"  id="id_message_send_input" style="display:none;"></textarea><br>
{% for question in questions reversed %}
{% if question.user == request.user %}
    {# Display the question since the current user owns it #}
    <p class="question">{{ question.question }}</p><br>
{% endif %}
{% endfor %}
        <div class="flex_button">
            <input class="hero_logo invisible" type="file" id="id_file_input">
            <button type="submit" class="send_button" id="id_message_send_button" style="display: none;">Send</button>
        </div>
        <br />
        <br />
    </div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<form action="" method="POST">
     {% csrf_token %}
     {{form.as_p}}
    <h1>Login</h1><br>
    <p> Please Enter your details here</p><br>
    <input type="text" class="field" placeholder="Username/Nick Name" name="un" required><br>
    <input type="password" class="field" placeholder="Your Password" name="pa" required><br>
    <div class="niche">
        New User? <i><a href="register" >Register</a></i>
    </div><br>
<!--    <a href="password-reset">Forgot Password?</a><br>-->
    <input type="submit" class="btn" value="Login" name="login">

    {% for m in messages %}
    <center><font color="red"><h2>{{m}}</h2></font></center>
    {% endfor %}
</form>

{% endblock %}

templates/question.html
{% extends 'base2.html' %}
{% block content %}
{% load static %}
<img class="toggle" src="{% static 'svg/chevron_left.svg' %}" onclick="toggleSidebar()">
<h3>{{request.user}} Keep a secret. I promise i wont tell anyone.</h3>
    <br>

    <div class="chat_container"></div>
    <div class="chat__item__container" id="id_chat_item_container" style="font-size: 20px">
        <br />
        <a class=" view" href="{% url 'question:list_question' %}">View secrets</a>
<br/>
        <textarea type="text" class="text_area" cols="20" rows="10"  onkeyup="if (this.scrollHeight > this.clientHeight) this.style.height = this.scrollHeight + 'px';"  id="id_message_send_input" style="display:none;"></textarea><br>
        <form method="post">
            {% csrf_token %}
            <input class="input" type="text" id="question" name="question" placeholder="Enter your Secret" required>
            <button class="send_button" type="submit">Keep</button>
        </form>
        <div class="flex_button">
            <input class="hero_logo invisible" type="file" id="id_file_input">
            <button type="submit" class="send_button" id="id_message_send_button" style="display: none;">Send</button>
        </div>
        <br />
        <br />
    </div>

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<form action="/register" method="POST">
    {% csrf_token %}
    <h1>Register</h1><br>
    <p> Please Enter your details here</p><br>
    <input type="text" class="field" placeholder="Username/Nickname" name="username" required><br/>
    <input type="email" class="field" placeholder="example@gmail.com" name="email" required><br/>
    <input type="password" class="field" placeholder="******" name="p1" required><br/>
    <input type="password" class="field" placeholder="******" name="p2" required><br/>
    <div class="niche">
        Already have an account? <i><a href="/" >login</a></i>
    </div><br>
    <input type="submit" class="btn" value="Register">
    {% for m in messages %}
    <center><font color="red"><h2>{{m}}</h2></font></center>
    {% endfor %}
</form>
{% endblock %}